version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Build started on `date`
      - echo Training the model...
      - python train.py
      - echo Model training completed on `date`
  post_build:
    commands:
      - echo Zipping artifacts...
      - zip -r function.zip lambda_function.py model.pkl appspec.yml scripts/ .
      - echo Uploading to S3...
      - aws s3 cp function.zip s3://traindata-pyxer1/
      - echo Updating Lambda function code...
      - aws lambda update-function-code --function-name pyxer --s3-bucket traindata-pyxer1 --s3-key function.zip

artifacts:
  files:
    - function.zip
  discard-paths: yes
  base-directory: .
