version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Training the model..."
      - python train.py
      - echo "Model training completed on `date`"
  post_build:
    commands:
      - echo "Cleaning up unnecessary files..."
      - find . -type d -name "tests" -exec rm -rf {} +
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -name "*.pyc" -delete
      - find . -name "*.pyo" -delete
      - find . -name "*.dist-info" -exec rm -rf {} +
      - find . -name "*.egg-info" -exec rm -rf {} +
      - echo "Creating deployment package..."
      - zip -r function.zip lambda_function.py appspec.yml scripts/ .
      - echo "Uploading deployment package to S3..."
      - aws s3 cp function.zip s3://traindata-pyxer1/
      - echo "Uploading model to S3..."
      - aws s3 cp model.pkl s3://traindata-pyxer1/model.pkl
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name pyxer --s3-bucket traindata-pyxer1 --s3-key function.zip

artifacts:
  files:
    - function.zip
  discard-paths: yes
  base-directory: .
