version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - echo "Updating submodules"
      - git config --global credential.helper 'cache --timeout=3600'
      - echo "machine github.com login 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 password x-oauth-basic" > ~/.netrc
      - git submodule update --init --recursive
      - echo "Installing project dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Training the model..."
      - python train.py
      - echo "Model training completed on $(date)"
  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deployment
      - cp -r * deployment/
      - cd deployment
      - zip -r ../deployment.zip .
      - cd ..
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deployment.zip s3://traindata-pyxer1/
artifacts:
  files:
    - deployment.zip
  discard-paths: yes
  base-directory: .