version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt -t ./python

  build:
    commands:
      - python -m unittest discover -s tests
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/python
      - python train.py
      - mkdir -p model
      - cp model.joblib model/model.joblib  # Ensure correct path
      - cp label_encoder.joblib model/label_encoder.joblib  # Ensure correct path
      - mkdir -p deployment_package
      - cp -r ./python/* ./deployment_package/
      - cp lambda_function.py appspec.yml model/model.joblib model/label_encoder.joblib ./deployment_package/
      - cd deployment_package
      - zip -r ../lambda_function.zip .
      - cd ..

artifacts:
  files:
    - lambda_function.zip
