version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt -t ./package

  build:
    commands:
      - cp -r ./package/* .
      - python train.py
      - mkdir -p model
      - cp model.joblib model/model.joblib  # Ensure correct path
      - cp label_encoder.joblib model/label_encoder.joblib  # Ensure correct path
      - zip -r lambda_function.zip lambda_function.py model/model.joblib model/label_encoder.joblib  # Ensure correct paths
      - cd package
      - zip -r ../lambda_function.zip .  # Add dependencies to the zip

artifacts:
  files:
    - lambda_function.zip
