version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Build started on `date`
      - echo Training the model...
      - python train.py
      - echo Model training completed on `date`
  post_build:
    commands:
      - echo Zipping artifacts...
      - cp model.pkl /tmp/model.pkl
      - zip -r function.zip .
      - echo Uploading to S3...
      - aws s3 cp function.zip s3://traindata-pyxer1/function.zip
      - echo Creating deployment...
      - aws deploy create-deployment --application-name pyxer --deployment-config-name CodeDeployLambdaCanary10Percent5Minutes --deployment-group-name deployins3 --s3-location bucket=traindata-pyxer1,bundleType=zip,key=function.zip
artifacts:
  files:
    - function.zip
  discard-paths: yes
  base-directory: .
