name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  SG_ROLE: ${{ secrets.AWS_SG_ROLE }}
  WORK_DIRECTORY: data
  PREFIX: DEMO-scikit-iris-gus
  FRAMEWORK_VERSION: 1.0-1
  SCRIPT_PATH: train.py
  INSTANCE_TYPE: ml.m5.large
  INITIAL_INSTANCE_COUNT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      # Train Model
      - name: Train Model
        run: |
          python app.py
